### ISSUE TITLE
Question about package structure and hexagonal architecture

### ISSUE THREAD

**Issue by svlada** [sustainablepace/humbledev#3]
Great series of articles on DDD. I've really enjoyed it.

I still have some dilemmas around some of the architectural elements. 

1. What is your approach for structuring projects using hexagonal architecture (gradle modules and package layout)? 

2. We usually have many bounded contexts within a single app. Should we:
2.1.  Introduce hard boundaries between bounded contexts, each bounded context having its own maven/gradle module with application/domain packages. Each of the bounded contexts would have a separate infrastructure module implementing rest/persistence. 
2.2. Have a single maven/gradle module structured using package by feature where each of the features would have application/domain packages. Infrastructure would reside in a separate maven/gradle module one module for rest-api and another one for persistence.
2.3. For both 2.1 and 2.2 we need a `combiner` module that would package modules like a lego.

The following is my current understanding of the hexagonal architecture:

```
1. Application
	1. UseCase interface 
	2. UseCase implementation 
		1. Use repository interface from the domain
	3. Command objects are self-validating 
2. Domain
	1. Entities
		1. Self-validating
	2. SPI
		1. Output Port - Repository interface
3. Infrastructure
	1. Adapters
		1. Rest
			1. Includes application module
			2. Spring Controllers
				1. DTO Validation
				2. Create command and invoke use case
		2. Persistence
			1. Includes domain module
			2. Implement repository using JDBI
4. Bootstrap
	1. SpringBootApplication launcher
	2. Maven project includes modules
	3. Load Application/Domain services into the Spring context by scanning @DomainService annotations.
```

**Comment by sustainablepace** [comment]
Hi Vlada, thanks for reaching out. It's hard to answer these questions, because I don't know anything about the context you're using hexagonal architecture. If you want to we can schedule a 30 min call. I have some time next week on Monday or Tuesday. I also followed you on Twitter, feel free to contact me there.
